✨ gains numeric `sum_with_threads`
r-staceans/blazr pull request #25
Opened 2024-12-15 03:21 UTC by jibarozzo

This PR enhances the functionality of the  `sum_with_threads` function to support both integer and double numeric types. 

Initially, the approach of handling both types via `NumericSexp` was considered, but this was not feasible due to the fact that `NumericSexp` does not implement the `to_vec()` method, which is necessary for the operation. Following the compiler suggestions, the solution was to use a match expression within `sum_with_threads` to explicitly handle two distinct types of numeric data: `IntegerSexp` for integers and `RealSexp` for doubles. This enables the function to process both types separately via two implementation.

2024-12-15 04:21 UTC, jonocarroll commented
I don't know where better to put this - I was curious about the difference between `thread` and `rayon` and had a go at [building a comparison myself](https://github.com/jonocarroll/rayon_vs_thread/blob/main/src/main.rs). Rayon seems easier to set up, unless you want to specify the number of threads and re-use a thread pool, but even then it wasn't so bad. 

What surprised me was that compared to just doing `x.iter().sum()` it's a lot more overhead and it's not clear that it's worth it, at least for the 'sum this random data' test case I implemented

```
> cargo run --release

567270539
Sum with single thread: 56.96µs
567270539
Sum with 2 threads: 229.21µs
567270539
Sum with rayon (2 threads): 173.04µs
567270539
Sum with 4 threads: 185.79µs
567270539
Sum with rayon (4 threads): 101.29µs
567270539
Sum with 8 threads: 229.67µs
567270539
Sum with rayon (8 threads): 276.13µs
```

Maybe I implemented something wrong - I haven't played with multithreading in Rust before, so this is a great opportunity for me to learn.

2024-12-16 08:09 UTC, jdhoffa requested changes
One tiny NIT comment on style, but functionally looks great!

I tested this by: 
* Reviewing the added unit test to ensure we are testing for the new behavious
* Syntactically reviewing the code
* Pulling and building locally, and testing out the functionality in a live R session

2024-12-16 08:09 UTC, jdhoffa commented on src/rust/src/lib.rs
> +    }
And for posterity, this `match` method of approaching integer or float inputs is what is suggested in `savvy` documentation here: 
https://yutannihilation.github.io/savvy/guide/type-overview.html

2024-12-16 19:50 UTC, jdhoffa approved these changes

2024-12-16 19:55 UTC, merged